/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project.rayedchan.swing.gui;

import Thor.API.Exceptions.tcAPIException;
import Thor.API.Exceptions.tcColumnNotFoundException;
import Thor.API.Exceptions.tcInvalidLookupException;
import Thor.API.Operations.tcLookupOperationsIntf;
import java.awt.Component;
import java.awt.Dialog;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import project.rayedchan.exception.BadFileFormatException;
import project.rayedchan.exception.LookupNameNotFoundException;
import project.rayedchan.services.OIMClientResourceAttr;
import project.rayedchan.services.tcOIMDatabaseConnection;
import project.rayedchan.utilities.LookupUtility;

/**
 *
 * @author oracle
 */
public class WelcomeJFrame extends javax.swing.JFrame {

    private OIMClientResourceAttr oimClientResAttr;
    private tcOIMDatabaseConnection dbConnection;
    
    /**
     * Creates new form WelcomeJFrame
     */
    public WelcomeJFrame(OIMClientResourceAttr oimClientResAttr, tcOIMDatabaseConnection dbConnection) {
        initComponents();
        setTitle("Welcome");
        setLocationRelativeTo(null); //This will center the JFrame in the middle of the screen
        setResizable(false); //Frame not resizable 
        setVisible(true);
        this.oimClientResAttr = oimClientResAttr;
        this.dbConnection = dbConnection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lookupDialog = new javax.swing.JDialog();
        lookup_Panel = new javax.swing.JPanel();
        lookup_lookupNameLbl = new javax.swing.JLabel();
        lookup_fileNameLbl = new javax.swing.JLabel();
        lookup_OperationLbl = new javax.swing.JLabel();
        lookup_lookupNameFld = new javax.swing.JTextField();
        lookup_fileNameFld = new javax.swing.JTextField();
        lookup_browseFileBtn = new javax.swing.JButton();
        lookup_addRadioBtn = new javax.swing.JRadioButton();
        lookup_deleteRadioBtn = new javax.swing.JRadioButton();
        lookup_exportRadioBtn = new javax.swing.JRadioButton();
        lookup_submitBtn = new javax.swing.JButton();
        lookup_cancelBtn = new javax.swing.JButton();
        processFormFieldDialog = new javax.swing.JDialog();
        fileChooser = new javax.swing.JFileChooser();
        lookup_buttonOpGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lookupBtn = new javax.swing.JButton();
        processFormFieldBtn = new javax.swing.JButton();
        processTaskBtn = new javax.swing.JButton();
        reconFieldBtn = new javax.swing.JButton();
        rfToPffMappingBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();

        lookup_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lookup Utility", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        lookup_lookupNameLbl.setText("Lookup Name:");

        lookup_fileNameLbl.setText("File Name:");

        lookup_OperationLbl.setText("Operation:");

        lookup_fileNameFld.setEditable(false);

        lookup_browseFileBtn.setText("Browse");
        lookup_browseFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookup_browseFileBtnActionPerformed(evt);
            }
        });

        lookup_buttonOpGroup.add(lookup_addRadioBtn);
        lookup_addRadioBtn.setText("Add");

        lookup_buttonOpGroup.add(lookup_deleteRadioBtn);
        lookup_deleteRadioBtn.setText("Delete");

        lookup_buttonOpGroup.add(lookup_exportRadioBtn);
        lookup_exportRadioBtn.setText("Export");

        lookup_submitBtn.setText("Submit");
        lookup_submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookup_submitBtnActionPerformed(evt);
            }
        });

        lookup_cancelBtn.setText("Cancel");
        lookup_cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookup_cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lookup_PanelLayout = new javax.swing.GroupLayout(lookup_Panel);
        lookup_Panel.setLayout(lookup_PanelLayout);
        lookup_PanelLayout.setHorizontalGroup(
            lookup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lookup_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lookup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lookup_PanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lookup_addRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lookup_deleteRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lookup_exportRadioBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lookup_PanelLayout.createSequentialGroup()
                        .addGroup(lookup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lookup_PanelLayout.createSequentialGroup()
                                .addGroup(lookup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lookup_lookupNameLbl)
                                    .addComponent(lookup_fileNameLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(lookup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lookup_lookupNameFld)
                                    .addGroup(lookup_PanelLayout.createSequentialGroup()
                                        .addComponent(lookup_fileNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lookup_browseFileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))))
                            .addGroup(lookup_PanelLayout.createSequentialGroup()
                                .addComponent(lookup_OperationLbl)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(lookup_PanelLayout.createSequentialGroup()
                                .addComponent(lookup_submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lookup_cancelBtn)))
                        .addContainerGap())))
        );

        lookup_PanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lookup_cancelBtn, lookup_submitBtn});

        lookup_PanelLayout.setVerticalGroup(
            lookup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lookup_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lookup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lookup_lookupNameLbl)
                    .addComponent(lookup_lookupNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(lookup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lookup_fileNameLbl)
                    .addComponent(lookup_fileNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lookup_browseFileBtn))
                .addGap(12, 12, 12)
                .addComponent(lookup_OperationLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lookup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lookup_addRadioBtn)
                    .addComponent(lookup_deleteRadioBtn)
                    .addComponent(lookup_exportRadioBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(lookup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lookup_submitBtn)
                    .addComponent(lookup_cancelBtn))
                .addGap(26, 26, 26))
        );

        lookup_PanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lookup_cancelBtn, lookup_submitBtn});

        javax.swing.GroupLayout lookupDialogLayout = new javax.swing.GroupLayout(lookupDialog.getContentPane());
        lookupDialog.getContentPane().setLayout(lookupDialogLayout);
        lookupDialogLayout.setHorizontalGroup(
            lookupDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lookup_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lookupDialogLayout.setVerticalGroup(
            lookupDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lookup_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lookupDialog.getAccessibleContext().setAccessibleParent(null);

        javax.swing.GroupLayout processFormFieldDialogLayout = new javax.swing.GroupLayout(processFormFieldDialog.getContentPane());
        processFormFieldDialog.getContentPane().setLayout(processFormFieldDialogLayout);
        processFormFieldDialogLayout.setHorizontalGroup(
            processFormFieldDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        processFormFieldDialogLayout.setVerticalGroup(
            processFormFieldDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        fileChooser.setFileFilter(new MyCustomFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Utility Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        lookupBtn.setText("Lookups");
        lookupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookupBtnActionPerformed(evt);
            }
        });

        processFormFieldBtn.setText("Process Form Fields");
        processFormFieldBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processFormFieldBtnActionPerformed(evt);
            }
        });

        processTaskBtn.setText("Process Tasks");

        reconFieldBtn.setText("Reconciliation Fields");

        rfToPffMappingBtn.setText("Recon Field Mappings");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(2);
        jTextArea1.setText("Updates an existing lookup by adding \nor removing entries.");
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(2);
        jTextArea2.setText("Updates an existing process form by\nadding or removing fields. ");
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(2);
        jTextArea3.setText("Creates update process tasks for \nan existing Process Definition.");
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setRows(2);
        jTextArea4.setText("Updates an exisitng resource object by\nadding or removing reconciliation fields.");
        jScrollPane4.setViewportView(jTextArea4);

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setRows(3);
        jTextArea5.setText("Updates an exisitng Process Definition \nby adding or removing recon field to\nprocess form field mappings.");
        jScrollPane5.setViewportView(jTextArea5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(processTaskBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(reconFieldBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(rfToPffMappingBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lookupBtn)
                            .addGap(48, 48, 48)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(processFormFieldBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1))
                    .addComponent(jSeparator4))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lookupBtn, processFormFieldBtn, processTaskBtn, reconFieldBtn, rfToPffMappingBtn});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3, jScrollPane4, jScrollPane5});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lookupBtn)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(processFormFieldBtn)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(processTaskBtn)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reconFieldBtn)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rfToPffMappingBtn)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lookupBtn, processFormFieldBtn, processTaskBtn, reconFieldBtn, rfToPffMappingBtn});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lookupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookupBtnActionPerformed
        // TODO add your handling code here:
       clearLookupUtilityFields();
         
       lookupDialog.setTitle("Lookup Utility Option");
       lookupDialog.pack();
       lookupDialog.setLocationRelativeTo(null); //This will center the JFrame in the middle of the screen
       lookupDialog.setResizable(true);
       lookupDialog.setModalityType(Dialog.ModalityType.APPLICATION_MODAL); //Modal dialog blocks input from top-level windows
       lookupDialog.setVisible(true); //Display lookup dialog
    }//GEN-LAST:event_lookupBtnActionPerformed

    private void processFormFieldBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processFormFieldBtnActionPerformed
        // TODO add your handling code here:
       processFormFieldDialog.setTitle("Process Form Field Option");
       processFormFieldDialog.pack();
       processFormFieldDialog.setLocationRelativeTo(null); //This will center the JFrame in the middle of the screen
       processFormFieldDialog.setResizable(true);
       processFormFieldDialog.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
       processFormFieldDialog.setVisible(true); //Display lookup dialog
    }//GEN-LAST:event_processFormFieldBtnActionPerformed

    private void lookup_browseFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookup_browseFileBtnActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this); //Open file chooser dialog
        if (returnVal == JFileChooser.APPROVE_OPTION) 
        {
            File file = fileChooser.getSelectedFile(); //Get details of selected file
            lookup_fileNameFld.setText(file.getAbsolutePath()); //Populate file name field
        }
        
        else 
        {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_lookup_browseFileBtnActionPerformed

    private void lookup_cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookup_cancelBtnActionPerformed
        // TODO add your handling code here:
        lookupDialog.dispose();
    }//GEN-LAST:event_lookup_cancelBtnActionPerformed

    private void lookup_submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookup_submitBtnActionPerformed
        // TODO add your handling code here:
         
        tcLookupOperationsIntf lookupOps = null;
        try
        {
            String lookupName = lookup_lookupNameFld.getText();
            String fileName = lookup_fileNameFld.getText();
            lookupOps = oimClientResAttr.getOIMClient().getService(tcLookupOperationsIntf.class);

            System.out.println("Lookup Name: " + lookupName);
            System.out.println("File Name: " + fileName);

            //Add entries to lookup
            if(lookup_addRadioBtn.isSelected())
            {
                try 
                {
                    LookupUtility.addEntriesToLookupDSFF(lookupOps, lookupName, fileName);
                    errorDialogMessage(lookupDialog, "Add successful.");
                    lookupDialog.dispose();
                } catch (BadFileFormatException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "Bad File format.");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "File not found.");
                } catch (IOException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "Reading file issue.");
                } catch (LookupNameNotFoundException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "Lookup Definition does not exist.");
                } catch (tcAPIException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "Add failed.");
                } catch (tcColumnNotFoundException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "Add failed.");
                } catch (tcInvalidLookupException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "Lookup Definition does not exist.");
                }
            }

            else if(lookup_deleteRadioBtn.isSelected())
            {
                try {
                    LookupUtility.deleteEntriesFromLookupDSFF(lookupOps,lookupName, fileName);
                    errorDialogMessage(lookupDialog, "Delete successful.");
                    lookupDialog.dispose();
                } catch (tcAPIException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "Delete failed.");
                } catch (tcInvalidLookupException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "Lookup Definition does not exist.");
                } catch (tcColumnNotFoundException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "Delete failed.");
                } catch (LookupNameNotFoundException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "Lookup Definition does not exist.");
                } catch (BadFileFormatException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "Bad File format.");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "File not found.");
                } catch (IOException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "Reading file issue.");
                }
            }

            else if(lookup_exportRadioBtn.isSelected())
            {
                try {
                    LookupUtility.exportLookupFileFormat(lookupOps, lookupName, fileName);                  
                    errorDialogMessage(lookupDialog, "Export successful.");
                    lookupDialog.dispose();
                } catch (tcAPIException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "Export failed.");
                } catch (tcInvalidLookupException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "Lookup Definition does not exist.");
                } catch (tcColumnNotFoundException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "Export failed.");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "File not found.");
                } catch (UnsupportedEncodingException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (LookupNameNotFoundException ex) {
                    Logger.getLogger(WelcomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    errorDialogMessage(lookupDialog, "Lookup Definition does not exist.");
                }
            }

            else
            {
                errorDialogMessage(lookupDialog, "An operation must be selected.");
            }
        }
        
        finally
        {
            if(lookupOps != null)
            {
                lookupOps.close();
            }
        }
        
    }//GEN-LAST:event_lookup_submitBtnActionPerformed

    private void errorDialogMessage(Component component, String message)
    {
        JOptionPane.showMessageDialog(component, message);
    }
    
    private void clearLookupUtilityFields()
    {
        lookup_lookupNameFld.setText("");
        lookup_fileNameFld.setText("");
        lookup_buttonOpGroup.clearSelection(); 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JButton lookupBtn;
    private javax.swing.JDialog lookupDialog;
    private javax.swing.JLabel lookup_OperationLbl;
    private javax.swing.JPanel lookup_Panel;
    private javax.swing.JRadioButton lookup_addRadioBtn;
    private javax.swing.JButton lookup_browseFileBtn;
    private javax.swing.ButtonGroup lookup_buttonOpGroup;
    private javax.swing.JButton lookup_cancelBtn;
    private javax.swing.JRadioButton lookup_deleteRadioBtn;
    private javax.swing.JRadioButton lookup_exportRadioBtn;
    private javax.swing.JTextField lookup_fileNameFld;
    private javax.swing.JLabel lookup_fileNameLbl;
    private javax.swing.JTextField lookup_lookupNameFld;
    private javax.swing.JLabel lookup_lookupNameLbl;
    private javax.swing.JButton lookup_submitBtn;
    private javax.swing.JButton processFormFieldBtn;
    private javax.swing.JDialog processFormFieldDialog;
    private javax.swing.JButton processTaskBtn;
    private javax.swing.JButton reconFieldBtn;
    private javax.swing.JButton rfToPffMappingBtn;
    // End of variables declaration//GEN-END:variables
}

class MyCustomFilter extends javax.swing.filechooser.FileFilter {
        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".txt");
        }
        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "Text documents (*.txt)";
        }
} 
